name: 'CI'
on:
  push:
    tags:
      - 'v*'
jobs:
  build-docker-image:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_KEY }}

      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

      - name: Build image and push to Docker Hub and GitHub Container Registry
        uses: docker/build-push-action@v5
        with:
          tags: |
            mattgialelis/lgtm-lbac-proxy:${{ steps.get_version.outputs.VERSION }}
            mattgialelis/lgtm-lbac-proxy:latest
          push: true
